### ISSUE TITLE
How to apply the query to all blocks (not only tasks with "todo"markers or such? 

### ISSUE THREAD

**Issue by Simeonh2021** [mlanza/logseq-classy#1]
Hi, mlanza. It's me again. I'm trying to apply "overdue", "future", and "distant future" to all blocks instead of those with task markers only. I've tried myself by deleting some sentences (👉👉[(contains? #{\"TODO\",\"DOING\"} ?marker)]). Sadly, it seems not working. Would you help? Many thanks.

**Comment by Simeonh2021** [comment]
![my try](https://user-images.githubusercontent.com/90461274/168461918-288cfa48-9da9-4c16-9d4a-8f9d246cbceb.jpg)

**Comment by mlanza** [comment]
It's easy to apply the queries to all blocks.  Just drop the marker portion of the query:

```json
{
  "disabled": false,
  "queries": [
    {
      "query": "[:find (pull ?block [*]) :where (or [?block :block/scheduled ?d] [?block :block/deadline ?d]) [(< ?d {0})]]",
      "inputs": [
        "today 0"
      ],
      "classname": "overdue",
      "matches": [],
      "disabled": false,
      "refreshRate": 10
    },
    {
      "query": "[:find (pull ?block [*]) :where (or [?block :block/scheduled ?d] [?block :block/deadline ?d]) [(> ?d {0})]]",
      "inputs": [
        "today 0"
      ],
      "classname": "future",
      "matches": [],
      "disabled": false,
      "refreshRate": 10
    },
    {
      "query": "[:find (pull ?block [*]) :where (or [?block :block/scheduled ?d] [?block :block/deadline ?d]) [(> ?d {0})]]",
      "inputs": [
        "today 90"
      ],
      "classname": "distant-future",
      "matches": [],
      "disabled": false,
      "refreshRate": 10
    }
  ]
}
```

But that's not your real issue.  If you look at the CSS I provided:

```css
.distant-future {
  opacity: .5;
  transition: all .6s ease-in-out;
  cursor: pointer;
}
.distant-future:hover {
  opacity: 1;
  transition: all .6s ease-in-out;
}
.distant-future a.TODO::after,
.distant-future a.DOING::after,
.distant-future a.WAITING::after {
  content: " 🔮" !important;
}
.overdue a.TODO::after,
.overdue a.DOING::after,
.overdue a.WAITING::after {
  content: " ⌛" !important;
}
```

The `distant-future` rule targets the block elements.  The other `::after` rules which add content emojis target the marker elements.  These are the rules for my own personal stylesheet, but stylesheets can be as custom as a person needs.  

The trouble is, the plugin assumes an understanding of CSS.  When I work out my stylesheet I open Logseq Developer Tools.  I use the tools to look under the hood in the way you can in most modern browsers, since Logseq is just a browser.  Then I interrogate the DOM.  That is, I dig down into the page and work out the structure of the DOM, in particular the elements I want to target, then I write my rules accordingly.  This step is necessary for anyone crafting custom stylesheets.  Otherwise, you're working blind.

And there's thousands of ways to craft your own customizations but you're not going to be able to skate by without knowing some CSS and without inspecting the structure of the DOM.

If you have no understanding of CSS, you're going to want to stick with the basic, top-level selectors and not try anything fancy, but you're not going to get the fine-grained styles you might like:

```css
.distant-future {
  opacity: .5;
}
.future {
  font-style: italic;
}
.overdue {
  color: red;
}
```
